### PR TITLE
First test and some refactoring

### PR DESCRIPTION
**Pull request by dmr**
This commit might be too messy to merge but it should give you an idea of how I want to continue with this.
What do you think?

### CODE REVIEW

**Comment by adamfeuer** [comment]
@dmr This looks good - I would like to use [pytest](http://pytest.org/latest/) as a test framework to run the tests, have you used it or would you be interested in using it? Here's a [pytest introduction](http://pythontesting.net/framework/pytest/pytest-introduction/) in case you are interested.

Alternatively you could use [python's unittest library]() - [nose](https://nose.readthedocs.org/en/latest/) and pytest can run those kind of tests too.

If that sounds good to you, run_tests() might instead be a test class with a test method (and where new test methods in the same group could be added).

Another couple of things I have been thinking about, and would love your thoughts about , are:

* How to simulate time passing? It would be nice to have a central place in the script that knew about time, so the unit tests can make an hour, day, week, or month pass instantly, while the regular program performs normally when not under test.
* How to make the tests run really fast without touching the file system? Another way to make the tests run fast and be very unit-test like is to not touch the external file system during most of the tests. In other words, centralize file system manipulation, and in most of the tests, use a mock object instead of the file system. The file system code needs to be tested, but much of the rotation logic could be tested without it.

Ok, those are just some things I was thinking about - don't worry if they're too much or not inspiring, I can work on them later too.

Thanks for your help!

**Comment by dmr** [comment]
I also use pytest for some other projects and indeed, just naming the method correctly could be enough for now as you said :)

I prefer to have not sooo fast tests that touch the file system because I feel that real issues only occur with real operations especially with files but having any tests is good for now.

I'll rename the method to test_move_latest_backup or something.

Do you have any plans regarding packaging? If we had a real package then we could exclude the tests from the standard installation

**Comment by dmr** [comment]
@adamfeuer I included Travis-CI for tests.
You can see the results here: https://travis-ci.org/netsyno/rotate-backups

**Comment by adamfeuer** [comment]
@dmr Travis == awesome! :smile: :+1: 

We can do real packaging too. I haven't put much love into this recently, but am glad you are helping. Will think about the packaging and get back to you. Or if you have ideas, send over a pull request.

I will look at this PR in the next couple of days.

**Pull request merged**
